apiVersion: v1
kind: ConfigMap
metadata:
  name: application-config
data:
  application.yml: |
    greeter: Hello from application

    spring:
      datasource:
        url: jdbc:mysql://localhost:3306/demo
        username: root
        password: password
      jpa:
        hibernate:
          ddl-auto: validate

---
apiVersion: v1
kind: Secret
metadata:
  name: application-secret
type: Opaque
stringData:
  mysql-username: "admin"
  mysql-password: "12345678"