apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-deployment
spec:
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
        - image: dactien020796/k8s_demo
          name: application
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: application-secret
                  key: mysql-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: application-secret
                  key: mysql-password
          volumeMounts:
            - name: application-config-volume
              mountPath: "/config"
              readOnly: true
          ports:
            - containerPort: 8080
      volumes:
      - name: application-config-volume
        configMap:
          name: application-config
          items:
          - key: application.yml
            path: application.yml
